[package]
name = "coingecko"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
coingecko = "1.0.0"
tokio = "1.17.0"
